modifiers = {
    "sprite":"圖示",
    "targeted_modifier": "對...的效果",
    "equipment_bonus": "裝備加成",
    "ai_strategy": "AI傾向",
    "command_power":"指揮點花費",
    "custom_modifier_tooltip":"自訂提示",
    "name":'名稱',
    "hidden_modifier":"隱藏效果",
    "random":"隨機",
    "ai_will_do":"AI執行機率",
    
    "ai_desired_divisions_factor":"AI訓練部隊傾向",
    "ai_call_ally_desire_factor":"AI招喚盟友傾向",
    "ai_join_ally_desire_factor": "Ai加入戰爭傾向",
    "ai_focus_defense_factor":"AI防禦傾向",
    "ai_focus_aggressive_factor":"AI進攻傾向",
    "ai_get_ally_desire_factor": "AI傾向結盟",

    "political_power_gain":"每日政治點數增長",
    "political_power_cost": "每日政治點消耗",
    "political_power_factor":"政治點數增長係數",
    "stability_factor":"穩定度",
    "stability_weekly":"每週穩定度增長",
    "defensive_war_stability_factor":"防禦戰爭中穩定度變化",
    "offensive_war_stability_factor":"進攻戰爭中穩定度變化",
    "party_popularity_stability_factor":"執政黨支持率改變的穩定度",
    "war_stability_factor":"戰爭時的穩定度",
    "war_support_factor":"戰爭支持度",
    "weekly_casualties_war_support":"每週因傷亡改變的戰爭支持度",
    "weekly_bombing_war_support":"每週因轟炸改變的戰爭支持度",
    "weekly_convoys_war_support":"每週因破交改變的戰爭支持度",
    "consumer_goods_factor":"生活消費品系數",
    "weekly_manpower":"每週人力",
    "monthly_population":"每月人口",
    "exiled_government_weekly_manpower":"流亡政府每週人力",
    "conscription":"適役人口",
    "conscription_factor":"適役人口係數",
    "non_core_manpower":"非核心人力",
    "mobilization_speed":"動員速度",
    "research_speed_factor":"科研速度",
    "special_project_speed_factor":"特殊項目研究速度",
    "sp_tag_nuclear_warfare_speed_factor":"特殊項目-核武研究速度",
    "sp_tag_nuclear_power_speed_factor": "特殊項目-核能研究速度",
    "specialization_land_speed_factor": "特殊項目-陸軍研究速度",
    "specialization_air_speed_factor": "特殊項目-空軍研究速度",
    "specialization_naval_speed_factor": "特殊項目-海軍研究速度",
    "special_project_facility_supply_consumption_factor": "研究設施補給消耗",

    "max_command_power":"最大指揮點",
    "command_cap_increase": "最大指揮點增加",
    "max_command_power_mult": "最大指揮點數係數",
    "command_power_gain_mult": "指揮點增長係數",
    "command_power_gain": "每日指揮點增加",
    "command_abilities_cost_factor": "指揮官能力花費",

    "political_advisor_cost_factor":"政治顧問花費係數",
    "materiel_manufacturer_cost_factor":"裝備製造商花費",
    "trade_laws_cost_factor":"貿易法案花費係數",
    "mobilization_laws_cost_factor":"動員法案花費係數",
    "economy_cost_factor":"經濟法案花費係數",
    'high_command_cost_factor':"最高指揮部花費係數",
    "army_chief_cost_factor":"陸軍顧問花費係數",
    "navy_chief_cost_factor":"海軍顧問花費係數",
    "air_chief_cost_factor":"空軍顧問花費係數",
    "theorist_cost_factor":"理論家花費",
    "military_leader_cost_factor": "陸軍將領招募花費",
    "land_doctrine_cost_factor":"陸軍學說花費",
    "naval_doctrine_cost_factor": "海軍學說花費",
    "air_doctrine_cost_factor":"空軍學說花費",
    "grant_medal_cost_factor":"授勳花費",

    "experience_gain_army":'陸軍經驗增長',
    "experience_gain_army_factor":"陸軍經驗增長係數",
    "experience_gain_navy":"海軍經驗增長",
    "experience_gain_navy_factor": "海軍經驗增長係數",
    "experience_gain_airforce":"空軍經驗增長",
    "experience_gain_airforce_factor": "空軍經驗增長係數",

    "fascism_drift":"每日法西斯支持率改變",
    "neutrality_drift":"每日中立支持率改變",
    "communism_drift":"每日共產支持率改變",
    "democratic_drift": "每日民主支持率改變",
    "master_ideology_drift":"從屬國意識形態支持度改變",
    "drift_defence_factor": "意識形態改變抑制",
    "power_balance_weekly": "每週權力平衡變化",

    "fascism_acceptance":"法西斯接受度",
    "communism_acceptance":"共產主義接受度",
    "democratic_acceptance": "民主接受度",
    "neutrality_acceptance":"中立接受度",

    "opinion_gain_monthly_same_ideology_factor":"相同意識形態每月關係改變係數",
    "opinion_gain_monthly_same_ideology":"相同意識形態每月關係改變",
    "opinion_gain_monthly_factor":"每月關係改變係數",
    "opinion_gain_monthly": "改善關係評價",
    "faction_trade_opinion_factor":"陣營貿易影響",
    
    "justify_war_goal_time":"正當化戰爭所需時間",
    "justify_war_goal_when_in_major_war_time":"與主要國家戰爭時所需正當化戰爭的時間",
    "generate_wargoal_tension":"正當化戰爭目標產生的緊張度",
    "subversive_activites_upkeep": "顛覆活動花費",
    "enemy_justify_war_goal_time":"他國正當化我們戰爭目標所需時間",
    "foreign_subversive_activites":"他國顛覆活動成本",
    "trade_opinion_factor":"貿易影響力係數",
    "improve_relations_maintain_cost_factor":"改善關係維持花費",
    "surrender_limit":"投降極限",
    "max_surrender_limit_offset":"投降界線修正",
    "join_faction_tension": "加入陣營所需的緊張度",
    "guarantee_tension":"保障他國獨立所需的緊張度",
    "request_lease_tension":"請求租借法案需要的緊張度",
    "enemy_declare_war_tension":"他國正當化我國所需的緊張度",
    "lend_lease_tension": "租借法案所需的緊張度",
    "embargo_threshold_factor": "實施禁運所需的緊張度限制",
    "send_volunteers_tension": "派遣志願軍所需的緊張度",
    "embargo_cost_factor":"禁運成本",
    "legitimacy_gain_factor":"流亡時的合法性改變係數",
    "legitimacy_daily":"流亡時的合法性改變",
    "guarantee_cost":"保障獨立的花費",
    "annex_cost_factor": "併吞花費",
    "resource_trade_cost_bonus_per_factory":"每個工廠交易時能夠多得到的資源",

    "subjects_autonomy_gain":"附庸國自治度改變",
    'puppet_cost_factor': "附庸國花費",
    "autonomy_manpower_share": "附庸國人力需求",
    "autonomy_gain":"自治度增長",
    "autonomy_gain_global_factor":"自治度增長係數",
    "autonomy_gain_trade_factor": "貿易改變的自治度",
    "autonomy_gain_warscore_factor": "戰爭分改變的自治度",

    "send_volunteer_size":"志願軍規模",
    "send_volunteer_factor":"志願軍數量上限",
    "send_volunteer_divisions_required":"派遣志願軍所需最低的陸軍規模",
    "air_volunteer_cap":"航空志願隊上限",
    
    "industrial_capacity_factory":"工廠產出",
    "industrial_capacity_dockyard":"船塢產出",
    "production_speed_buildings_factor":"建造速度",
    "industry_repair_factor":"修復速度",
    "industry_free_repair_factor":"免費維修速度",
    "production_speed_rail_way_factor":"鐵路建造速度",
    "production_speed_infrastructure_factor": "基礎建設建造速度",
    "production_speed_industrial_complex_factor":"民用工廠建造速度",
    "production_speed_arms_factory_factor": "軍用工廠建造速度",
    "production_speed_dockyard_factor":"船塢建造速度",
    "production_speed_naval_base_factor":"海軍基地建造速度",
    "production_speed_synthetic_refinery_factor":"合成煉油廠建造速度",
    "production_speed_fuel_silo_factor":"儲油槽建造速度",
    "production_speed_supply_node_factor":"補給基地建造速度",
    "production_speed_air_base_factor":"空軍基地建造速度",
    "production_speed_bunker_factor":"陸上堡壘建造速度",
    "production_speed_coastal_bunker_factor":"岸防堡壘建造速度",
    "production_speed_anti_air_building_factor":"防空炮建造速度",
    "production_speed_rocket_site_factor":"火箭發射場建造速度",
    "production_speed_radar_station_factor":"雷達建造速度",
    "production_speed_nuclear_reactor_factor":"核反應堆建設速度",
    "specialization_nuclear_speed_factor":"特殊項目速度",
    "global_building_slots_factor":"可用的建築欄位",
    "global_building_slots":"可用建築欄位增加",
    "conversion_cost_civ_to_mil_factor": "民用轉軍用花費",
    "production_factory_efficiency_gain_factor":"生產效率增長",
    "production_factory_max_efficiency_factor":"最高生產效率",
    "production_factory_start_efficiency_factor":"基礎生產效率",
    "production_lack_of_resource_penalty_factor":"缺乏資源的生產效率改變",
    "line_change_production_efficiency_factor":"生產效率保持",
    "equipment_conversion_speed":"裝備轉換速度",
    "equipment_upgrade_xp_cost":"裝備經驗花費",
    "local_resources_factor":"資源獲得",
    "min_export":"資源出口",
    "country_resource_aluminium":"鋁獲得",
    "country_resource_oil":"油獲得",
    "country_resource_rubber":"橡膠獲得",
    "country_resource_tungsten":"鎢獲得",
    "country_resource_steel":"鐵獲得",
    "country_resource_chromium":"鉻獲得",

    "cat_mobile_warfare_cost_factor":"機動化作戰學說花費",
    "cat_superior_firepower_cost_factor":"優勢火力學說花費",
    "cat_grand_battle_plan_cost_factor":"決戰計畫學說花費",
    "cat_mass_assault_cost_factor": "人海突擊學說花費",
    "cat_strategic_destruction_cost_factor": "戰略破壞學說花費",
    "cat_battlefield_support_cost_factor": "戰場支援學說花費",
    "cat_operational_integrity_cost_factor":"連續作戰學說花費",
    "cat_base_strike_cost_factor":"基地打擊學說",
    "cat_fleet_in_being_cost_factor":"存在艦隊學說",
    "cat_trade_interdiction_cost_factor":"貿易阻斷學說",

    "military_industrial_organization_funds_gain":"軍工機構經費獲取",
    "military_industrial_organization_policy_cost":"軍工機構政策花費",
    "military_industrial_organization_design_team_assign_cost":"軍工組織設計花費",
    "military_industrial_organization_industrial_manufacturer_assign_cost":"軍工組織指派花費",
    "tank_manufacturer_cost_factor":"坦克製造商花費",
    "aircraft_manufacturer_cost_factor":"空軍製造商花費",
    "naval_manufacturer_cost_factor":"海軍製造商花費",
    "military_industrial_organization_research_bonus":"軍工組織研究加成",

    "resistance_growth_on_our_occupied_states":"敵方佔領抵抗增長係數",
    "resistance_decay_on_our_occupied_states": "敵方佔領抵抗衰減速度",
    "resistance_target_on_our_occupied_states":"敵方佔領抵抗目標",
    "resistance_damage_to_garrison_on_our_occupied_states": "敵方佔領傷害",
    "resistance_growth":"抵抗增長",
    "resistance_decay":"抵抗衰減",
    "resistance_target":"抵抗目標",
    "resistance_activity":"抵抗活動機率",
    "resistance_garrison_penetration_chance":"駐軍滲透機率",
    "resistance_damage_to_garrison":"衛戍損失",
    "required_garrison_factor":"衛戍人力",
    "root_out_resistance_effectiveness_factor": "根除抵抗效率",
    "compliance_gain":"順從度",
    "compliance_growth":"順從度增長",
    "compliance_growth_on_our_occupied_states":"敵方佔領順從度增長",

    "unit_cavalry_design_cost_factor":"騎兵編制設計花費",
    "cavalry_attack_factor": "騎兵攻擊",
    "cavalry_defence_factor": '騎兵防禦',
    "army_armor_attack_factor":"裝甲攻擊",
    "army_armor_defence_factor":"裝甲防禦",
    "army_artillery_attack_factor":"砲兵攻擊",
    "army_artillery_defence_factor":"砲兵防禦",
    "army_infantry_attack_factor":"步兵攻擊",
    "army_infantry_defence_factor":"步兵防禦",
    "motorized_attack_factor":"摩托化攻擊",
    "motorized_defence_factor":"摩托化防禦",
    "mechanized_attack_factor":"機械化攻擊",
    "mechanized_defence_factor":"機械化防禦",
    "modifier_army_sub_unit_militia_attack_factor":"民兵攻擊",
    "modifier_army_sub_unit_militia_defence_factor": "民兵防禦",
    "modifier_army_sub_unit_militia_max_org_factor":"民兵組織度",
    "modifier_army_sub_unit_mountaineers_attack_factor":"山地部隊攻擊",
    "modifier_army_sub_unit_mountaineers_speed_factor":"山地部隊移動速度",
    "modifier_army_sub_unit_mountaineers_max_org_factor":"山地部隊組織度",
    "army_attack_factor":"陸軍攻擊",
    "special_forces_attack_factor":"特種攻擊",
    "army_defence_factor": "陸軍防禦",
    "special_forces_defence_factor":"特種防禦",
    "army_org_factor":"組織度",
    "org_loss_when_moving": "移動時損失的組織度",
    "army_org_regain": "組織度回復",
    "army_morale_factor": "組織度回復率",
    "land_reinforce_rate": "增援率",
    "coordination_bonus": "協調性",
    "initiative_factor": "主動性",
    "army_speed_factor": "陸軍速度",
    "army_attack_speed_factor":"陸軍師進攻速度",
    "army_core_attack_factor":"核心領土攻擊",
    "army_core_defence_factor": "核心領土防禦",
    "army_attack_against_major_factor":"對主要國家的攻擊",
    "army_defence_against_major_factor":"對主要國家的防禦",
    "army_breakthrough_against_minor_factor":"對非主要國家的突破",
    "planning_speed":"計畫速度",
    "max_planning":"計畫上限",
    "max_planning_factor":"計畫上限係數",
    "dig_in_speed_factor":"塹壕速度",
    "max_dig_in":"塹壕上限",
    "max_dig_in_factor":"塹壕上限係數",
    "dont_lose_dig_in_on_attack":"攻擊而不失去塹壕",
    "minimum_training_level":"最小訓練程度",
    "max_training":"最大訓練",
    "training_time_factor":"訓練時間",
    "training_time_army_factor":"訓練時間係數",
    "special_forces_cap":"特種部隊上限係數",
    "special_forces_cap_flat":"特種部隊上限",
    "equipment_capture_factor":"裝備繳獲",
    "supply_node_range":"補給範圍",
    "out_of_supply_factor":"攜行補給",
    "special_forces_out_of_supply_factor":"特種部隊補給耗盡懲罰",
    "supply_combat_penalties_on_core_factor": "核心領土戰鬥補給耗盡懲罰",
    "supply_consumption_factor":"補給使用",
    "supply_factor":"補給效率",
    "fuel_gain_factor":"從石油中獲得的燃料",
    "base_fuel_gain_factor":"基礎燃料獲得",
    "air_fuel_consumption_factor":"空軍燃料使用",
    "navy_fuel_consumption_factor":"海軍燃料使用",
    "experience_gain_army_unit_factor":"陸軍師經驗增長",
    "experience_loss_factor":"有經驗士兵的損失",
    "land_night_attack":"夜間攻擊",
    "female_random_army_leader_chance":"女性將領出現機率",
    "experience_gain_army_factor":"陸軍經驗增長係數",
    "experience_gain_army": "陸軍經驗增長",
    "winter_attrition_factor":"冬季損耗",
    "attrition":"陸軍師損耗",
    "coastal_bunker_effectiveness_factor":"岸防堡壘效率",
    "land_bunker_effectiveness_factor":"堡壘效率",
    "naval_invasion_prep_speed": "海上入侵準備速度",
    "amphibious_invasion":"兩棲登陸速度",
    "paradrop_organization_factor":"空降後的組織度",
    "paratrooper_aa_defense":"傘兵對防空炮的防禦",

    "naval_coordination":"海軍協調性",
    "naval_morale_factor": "海軍組織度",
    "naval_night_attack": "海軍夜間攻擊",
    "naval_critical_score_chance_factor":"海軍致命一擊機率",
    "naval_strike_attack_factor":"對海轟炸",
    "naval_strike_targetting_factor":"對海瞄準",
    "naval_strike_agility_factor":"對海機動",
    "critical_receive_chance":"遭受致命一擊的機率",
    "experience_gain_navy": "海軍經驗增長",
    "experience_gain_navy_factor":"海軍經驗增長係數",
    "navy_capital_ship_attack_factor":"主力艦的攻擊",
    "navy_capital_ship_defence_factor":"主力艦的防禦",
    "navy_screen_attack_factor":"護衛艦的攻擊",
    "navy_screen_defence_factor":"護衛艦的防禦",
    "convoy_raiding_efficiency_factor":"襲擊任務效率",
    "naval_speed_factor":"海軍速度",
    "navy_submarine_detection_factor":"水下探測",
    "navy_anti_air_attack_factor":"海軍對空攻擊",
    "navy_max_range_factor":"海軍航程",
    "navy_submarine_attack_factor":"潛艇攻擊",
    "navy_submarine_defence_factor":"潛艇防禦",
    "sortie_efficiency":"海軍出擊效率",

    "enemy_army_bonus_air_superiority_factor":"敵方空優對陸軍的加成",
    "army_bonus_air_superiority_factor":"我方空優對陸軍的加成",
    "air_night_penalty":"空軍夜間懲罰",
    "rocket_attack_factor":"火箭傷害",
    "air_accidents_factor":"空難機率",
    "experience_gain_air_factor":"空軍經驗增長係數",
    "experience_gain_air": "空軍經驗增長",
    "air_training_xp_gain_factor":"空軍訓練經驗增長",
    "air_range_factor":"航程",
    "air_weather_penalty":"惡劣天氣懲罰",
    "air_ace_generation_chance_factor":"王牌飛行員產生機率",
    "air_intercept_efficiency":"攔截任務效率",
    "air_superiority_efficiency":"制空權",
    "air_cas_efficiency":"密接支援任務效率",
    "air_cas_present_factor":"密接支援",
    "ground_attack_factor":"對地攻擊",
    "air_strategic_bomber_defence_factor":"戰略轟炸機防禦",
    "air_strategic_bomber_bombing_factor":"戰略轟炸",
    "navy_carrier_air_attack_factor":"艦載機攻擊",
    "navy_carrier_air_targetting_factor":"艦載機空中瞄準",
    "navy_carrier_air_agility_factor":"艦載機機動",

    "operative_slot":"特工位",
    "agency_upgrade_time":"情報局升級時間",
    "encryption_factor":"加密能力係數",
    "decryption_power":"解密能力",
    "decryption_factor":"解膩能力係數",
    "army_intel_factor":"陸軍情報",
    "navy_intel_factor":"海軍情報",
    "airforce_intel_factor":"空軍情報",
    "civilian_intel_factor":"民政情報",
    "enemy_operative_detection_chance":"敵方間諜被發現機率",
    "intel_network_gain_factor":"情報網建設速度",
    "boost_ideology_mission_factor":"改變意識形態任務效率",
    "operation_coup_government_outcome":"策畫政變效率",
    "operation_infiltrate_outcome":"滲透效率",
    "operation_boost_resistance_outcome":"增加抵抗效率",
    "boost_resistance_factor":"加強抵抗組織效率",
    "operation_targeted_sabotage_industry_outcome":"破壞工業效率",
    "operation_targeted_sabotage_resources_outcome":"破壞資源效率",
    "operation_targeted_sabotage_infrastructure_outcome":"破壞基礎建設效率",
    "diplomatic_pressure_mission_factor":"外交施壓效率",
    "civilian_intel_to_others":"向他國洩漏的民政情報",
    "army_intel_to_others":"向他國洩漏的陸軍情報",
    "navy_intel_to_others":"向他國洩漏的海軍情報",
    "airforce_intel_to_others":"向他國洩漏的空軍情報",
    "intelligence_agency_defense":"反間諜",
    "own_operative_detection_chance_factor":"我方特工被發現機率",
    "enemy_operative_capture_chance_factor":"敵方特工被捕機率",
    "intel_from_operatives_factor":"從行動中獲得的情報",
    "army_intel_decryption_bonus":"陸軍破譯加成",
    "air_intel_decryption_bonus":"空軍破譯加成",
    "navy_intel_decryption_bonus":"海軍破譯加成",
    "civilian_intel_decryption_bonus":"民政破譯加成",
    "local_intel_to_enemies":"敵人獲取的情報",
    "intel_from_combat_factor": "從戰鬥中獲得的情報"
}